services:
  - type: web
    name: ubuntu-vps
    env: docker
    repo: https://github.com/your-username/render-ubuntu-docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
